---
title: "RSBS_PCA"
author: "Gwen"
date: "2023-11-20"
output: html_document
---

Packages needed
```{r}
library(ggplot2) # plotting
library(ggpubr) # plotting
library(tidyverse) # data manipulation
library(dplyr) # data manipulation
library(conStruct) #admixture mapping

library(raster) #Read in Raster datasets
library(sf) #Read in vector datasets
library(ggspatial)#Add some functionality to mapping spatial data with the ggplot2 framework
library(tmap) #Thematic mapping package

```


Genetic PCA (Norway spruce mapped)
```{r}

RS_COV <- as.matrix(read.table("RS_mapped_poly.cov")) # read in the genetic covariance matrix

RS_PCA <- eigen(RS_COV) # extract the principal components from the COV matrix

## How much variance is explained by the first few PCs?

RS_var <- round(RS_PCA$values/sum(RS_PCA$values),3)


RS_var[1:3] #[1] 0.189 0.025 0.010 (e=2)

# A "screeplot" of the eigenvalues of the PCA:

barplot(RS_var, 
        xlab="Eigenvalues of the PCA", 
        ylab="Proportion of variance explained")

## Bring in the bam.list file and extract the sample info:

RS_names <- read.table("RS_mapped_bam.list")
RS_names <- unlist(strsplit(basename(as.character(RS_names[,1])), split = ".sorted.rmdup.bam"))
split = strsplit(RS_names, "_")
RS_pops <- data.frame(RS_names[1:113], do.call(rbind, split[1:113]))
names(RS_pops) = c("Ind", "Pop", "Row", "Col")

## A quick and humble PCA plot:

plot(RS_PCA$vectors[,1:2],
     col=as.factor(RS_pops[,2]),
     xlab="PC1",ylab="PC2", 
     main="Genetic PCA")
     
## A more beautiful PCA plot using ggplot :)

RS_data=as.data.frame(RS_PCA$vectors)
RS_data=RS_data[,c(1:3)]
RS_data= cbind(RS_data, RS_pops)

cols=c("#377eB8","#d71868","#0A9396","#94D2BD","#8e7cc3","#005f73","#E26D5C","#AE2012", "#6d597a", "#7EA16B","#d4e09b", "gray70", "gold", "khaki1", "orange")

RS_PCA_plot <- ggscatter(RS_data, x = "V1", y = "V2",
          color = "Pop",
          mean.point = FALSE,
          star.plot = FALSE,
          size = 5) +
  theme_bw(base_size = 20, base_family = "Times") +
  theme(panel.background = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        plot.background = element_blank(), 
        legend.text=element_text(size=rel(.9)), 
        axis.text = element_text(size=13), 
        legend.position = "bottom") +
  labs(x = paste0("PC1: (",RS_var[1]*100,"%)"), y = paste0("PC2: (",RS_var[2]*100,"%)")) +
  scale_color_manual(values=c(cols), name="Source population") +
  guides(colour = guide_legend(nrow = 2))

```


```{r}
BS_COV <- as.matrix(read.table("BS_mapped_poly_e2.cov"))

BS_PCA <- eigen(BS_COV)# extract the principal components from the COV matrix

## How much variance is explained by the first few PCs?
BS_var <- round(BS_PCA$values/sum(BS_PCA$values),3)
BS_var[1:3] #[1] 0.196 0.028 0.010 (e=2)

# A "screeplot" of the eigenvalues of the PCA:

barplot(BS_var, 
        xlab="Eigenvalues of the PCA", 
        ylab="Proportion of variance explained")

## Bring in the bam.list file and extract the sample info:

BS_names <- read.table("BS_mapped_bam.list")
BS_names <- unlist(strsplit(basename(as.character(BS_names[,1])), split = ".sorted.rmdup.bam"))
BS_split = strsplit(BS_names, "_")
BS_pops <- data.frame(BS_names[1:113], do.call(rbind, BS_split[1:113]))
names(BS_pops) = c("Ind", "Pop", "Row", "Col")

## A quick and humble PCA plot:

plot(BS_PCA$vectors[,1:2],
     col=as.factor(BS_pops[,2]),
     xlab="PC1",ylab="PC2", 
     main="Genetic PCA")
     
## A more beautiful PCA plot using ggplot :)

BS_data=as.data.frame(BS_PCA$vectors)
BS_data=BS_data[,c(1:3)]
BS_data= cbind(BS_data, BS_pops)

cols=c("#377eB8","#d71868","#0A9396","#94D2BD","#8e7cc3","#005f73","#E26D5C","#AE2012", "#6d597a", "#7EA16B","#d4e09b", "gray70", "gold", "khaki1", "orange")

BS_PCA_plot <- ggscatter(BS_data, x = "V1", y = "V2",
          color = "Pop",
          mean.point = FALSE,
          star.plot = FALSE,
          size = 5) +
  theme_bw(base_size = 20, base_family = "Times") +
  theme(panel.background = element_blank(), 
        legend.background = element_blank(), 
        panel.grid = element_blank(), 
        plot.background = element_blank(), 
        legend.text=element_text(size=rel(.9)), 
        axis.text = element_text(size=13), 
        legend.position = "bottom") +
  labs(x = paste0("PC1: (",BS_var[1]*100,"%)"), y = paste0("PC2: (",BS_var[2]*100,"%)")) +
  scale_color_manual(values=c(cols), name="Source population") +
  guides(colour = guide_legend(nrow = 2))
```



Admixture clustering Norway spruce mapping
```{r}

# import the ancestry scores (these are the .Q files)

q <- read.table("RS_mapped_poly.admix.3.Q", sep=" ", header=F)

K=dim(q)[2] #Find the level of K modeled

## order according to population code
ord<-order(RS_pops[,2])

# make the plot:
barplot(t(q)[,ord],
        col=cols[1:K],
        space=0,border=NA,
        xlab="Populations",ylab="Admixture proportions",
        main=paste0("Spruce K=",K))
text(tapply(1:nrow(RS_pops),RS_pops[ord,2],mean),-0.05,unique(RS_pops[ord,2]),xpd=T)
abline(v=cumsum(sapply(unique(RS_pops[ord,2]),function(x){sum(RS_pops[ord,2]==x)})),col=1,lwd=1.2)
```

making admixture pie chart map
```{r}
### This is probably the messiest way to do this, but going to create a df with the average admixture proportions for each population ###

pop_admix <- bind_cols(RS_pops,q) # add the admixture proportions for each sample to population data in a new df

#"2019" "2020" "2021" "2022" "2024" "2027" "2030" "2032" "2100" "2101" "2103" "2505" "MN1" 
#[14] "MN2"  "WISC

# Separate out each population and find admixture averages
pop2019 <- pop_admix[pop_admix$Pop=="2019",] # keep only this population
pop2019 <- mutate(pop2019, v1_avg=mean(V1)) %>% mutate(pop2019, v2_avg=mean(V2)) %>% mutate(pop2019, v3_avg=mean(V3)) # add new columns with admixture averages
pop2019 <- pop2019[1,] #keep only the first row
pop2019 <- pop2019[c(2,8:10)] #keep only the Pop and averages columns

pop2020 <- pop_admix[pop_admix$Pop=="2020",]
pop2020 <- mutate(pop2020, v1_avg=mean(V1)) %>% mutate(pop2020, v2_avg=mean(V2)) %>% mutate(pop2020, v3_avg=mean(V3)) 
pop2020 <- pop2020[1,]
pop2020 <- pop2020[c(2,8:10)] 

pop2021 <- pop_admix[pop_admix$Pop=="2021",]
pop2021 <- mutate(pop2021, v1_avg=mean(V1)) %>% mutate(pop2021, v2_avg=mean(V2)) %>% mutate(pop2021, v3_avg=mean(V3)) 
pop2021 <- pop2021[1,]
pop2021 <- pop2021[c(2,8:10)] 

pop2022 <- pop_admix[pop_admix$Pop=="2022",]
pop2022 <- mutate(pop2022, v1_avg=mean(V1)) %>% mutate(pop2022, v2_avg=mean(V2)) %>% mutate(pop2022, v3_avg=mean(V3)) 
pop2022 <- pop2022[1,]
pop2022 <- pop2022[c(2,8:10)] 

pop2024 <- pop_admix[pop_admix$Pop=="2024",]
pop2024 <- mutate(pop2024, v1_avg=mean(V1)) %>% mutate(pop2024, v2_avg=mean(V2)) %>% mutate(pop2024, v3_avg=mean(V3)) 
pop2024 <- pop2024[1,]
pop2024 <- pop2024[c(2,8:10)] 

pop2027 <- pop_admix[pop_admix$Pop=="2027",]
pop2027 <- mutate(pop2027, v1_avg=mean(V1)) %>% mutate(pop2027, v2_avg=mean(V2)) %>% mutate(pop2027, v3_avg=mean(V3)) 
pop2027 <- pop2027[1,]
pop2027 <- pop2027[c(2,8:10)] 

pop2030 <- pop_admix[pop_admix$Pop=="2030",]
pop2030 <- mutate(pop2030, v1_avg=mean(V1)) %>% mutate(pop2030, v2_avg=mean(V2)) %>% mutate(pop2030, v3_avg=mean(V3)) 
pop2030 <- pop2030[1,]
pop2030 <- pop2030[c(2,8:10)] 

pop2032 <- pop_admix[pop_admix$Pop=="2032",]
pop2032 <- mutate(pop2032, v1_avg=mean(V1)) %>% mutate(pop2032, v2_avg=mean(V2)) %>% mutate(pop2032, v3_avg=mean(V3)) 
pop2032 <- pop2032[1,]
pop2032 <- pop2032[c(2,8:10)] 

pop2100 <- pop_admix[pop_admix$Pop=="2100",]
pop2100 <- mutate(pop2100, v1_avg=mean(V1)) %>% mutate(pop2100, v2_avg=mean(V2)) %>% mutate(pop2100, v3_avg=mean(V3)) 
pop2100 <- pop2100[1,]
pop2100 <- pop2100[c(2,8:10)] 

pop2101 <- pop_admix[pop_admix$Pop=="2101",]
pop2101 <- mutate(pop2101, v1_avg=mean(V1)) %>% mutate(pop2101, v2_avg=mean(V2)) %>% mutate(pop2101, v3_avg=mean(V3)) 
pop2101 <- pop2101[1,]
pop2101 <- pop2101[c(2,8:10)] 

pop2103 <- pop_admix[pop_admix$Pop=="2103",]
pop2103 <- mutate(pop2103, v1_avg=mean(V1)) %>% mutate(pop2103, v2_avg=mean(V2)) %>% mutate(pop2103, v3_avg=mean(V3)) 
pop2103 <- pop2103[1,]
pop2103 <- pop2103[c(2,8:10)]

pop2505 <- pop_admix[pop_admix$Pop=="2505",]
pop2505 <- mutate(pop2505, v1_avg=mean(V1)) %>% mutate(pop2505, v2_avg=mean(V2)) %>% mutate(pop2505, v3_avg=mean(V3)) 
pop2505 <- pop2505[1,]
pop2505 <- pop2505[c(2,8:10)]

popMN1 <- pop_admix[pop_admix$Pop=="MN1",]
popMN1 <- mutate(popMN1, v1_avg=mean(V1)) %>% mutate(popMN1, v2_avg=mean(V2)) %>% mutate(popMN1, v3_avg=mean(V3)) 
popMN1 <- popMN1[1,]
popMN1 <- popMN1[c(2,8:10)]

popMN2 <- pop_admix[pop_admix$Pop=="MN2",]
popMN2 <- mutate(popMN2, v1_avg=mean(V1)) %>% mutate(popMN2, v2_avg=mean(V2)) %>% mutate(popMN2, v3_avg=mean(V3)) 
popMN2 <- popMN2[1,]
popMN2 <- popMN2[c(2,8:10)]

popWISC <- pop_admix[pop_admix$Pop=="WISC",]
popWISC <- mutate(popWISC, v1_avg=mean(V1)) %>% mutate(popWISC, v2_avg=mean(V2)) %>% mutate(popWISC, v3_avg=mean(V3)) 
popWISC <- popWISC[1,]
popWISC <- popWISC[c(2,8:10)]

pop_admix_avg <- bind_rows(pop2019,pop2020,pop2021,pop2022,pop2024,pop2027,pop2030,pop2032,pop2100,pop2101,pop2103,pop2505,popMN1,popMN2,popWISC) # then put them all the population averages into a single df
pop_admix_avg <- pop_admix_avg[,2:4] # removing population names since these can't be present for making the pie charts
pop_admix_avg <- as.matrix(pop_admix_avg) # converting to a matrix

pop_coords <- read_csv("RSBS_coordinates.csv") # csv with just latitude + longitude data
pop_coords <- pop_coords[,2:3] # removing population ID column
pop_coords <- as.matrix(pop_coords) # converting to a matrix

# setting up shapefiles for the map
n_america <- read_sf("shape_files/bound_p.shp") # this is a shp for all of north america with more generalized boundaries

canada <- n_america[n_america$COUNTRY == "CAN",c(-1,-2,-3)]
quebec <- canada[canada$NAME == "Quebec / Québec",]
nova_scotia <- canada[canada$NAME == "Nova Scotia / Nouvelle-Écosse",]
new_brunswick <- canada[canada$NAME == "New Brunswick / Nouveau-Brunswick",]
ontario <- canada[canada$NAME == "Ontario",]
canada_east <- bind_rows(quebec, nova_scotia, new_brunswick, ontario)

us <- n_america[n_america$COUNTRY == "USA",c(-1,-2,-3)]
east_states <- c("Connecticut","Maine","Massachusetts","New Hampshire","Rhode Island","Vermont","Delaware","District of Columbia","Florida","Georgia","Maryland","North Carolina","South Carolina","Virginia","West Virginia","Iowa","Missouri","Minnesota","New Jersey","New York","Pennsylvania","Illinois","Indiana","Michigan","Ohio","Wisconsin","Alabama","Kentucky","Mississippi","Tennessee","Arkansas")
us_east <- us[us$NAME %in% east_states,]

total_east_coast <- bind_rows(canada_east,us_east)

par(bg = 'lightsteelblue1')
#plotting the map with the admixture proportions over it
plot(total_east_coast[,6], reset=FALSE, col="gray90", main="Population Admixture Proportions")
legend("topleft", c("Refugia", "Northern", "Black Spruce"), col = c("darkolivegreen", "dodgerblue", "goldenrod1"), pch=20)
make.admix.pie.plot(admix.proportions = pop_admix_avg,
                    coords = pop_coords,
                    layer.colors = c("goldenrod1", "dodgerblue", "darkolivegreen"),
                    radii = 1.5,
                    add = TRUE,
                    x.lim = NULL,
                    y.lim = NULL)


```



